services:
  app:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - migrate
      - db
    env_file:
      - .env
    networks:
      - nostr_search_net
  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    depends_on:
      - migrate
      - db
    volumes:
      - ./indexer/config.json:/app/config.json
    env_file:
      - .env
    networks:
      - nostr_search_net
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "18080:80"
    depends_on:
      - app
    networks:
      - nostr_search_net
  db:
    image: postgres:15
    environment:
      # Map PG* variables to POSTGRES_* variables expected by container
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_min_messages=${DB_LOG_LEVEL:-warning}", "-c", "log_statement=${DB_LOG_STATEMENT:-none}"]
    networks:
      - nostr_search_net
  migrate:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    command: ["python", "migrate.py"]
    networks:
      - nostr_search_net

networks:
  nostr_search_net:
    driver: bridge

volumes:
  postgres_data:
