version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8008:8000"
    depends_on:
      - db
    environment:
      PGDATABASE: nostr
      PGUSER: nostr
      PGPASSWORD: nostr
      PGHOST: db
      PGPORT: 5432
  indexer:
    build:
      context: .
      dockerfile: indexer/Dockerfile
    depends_on:
      - db
    volumes:
      - ./indexer/config.json:/app/config.json
    environment:
      PGDATABASE: nostr
      PGUSER: nostr
      PGPASSWORD: nostr
      PGHOST: db
      PGPORT: 5432
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nostr
      POSTGRES_USER: nostr
      POSTGRES_PASSWORD: nostr
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
