[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "bech32>=1.2.0",
    "fastapi>=0.110.0",
    "uvicorn>=0.23.0",
    "psycopg2-binary>=2.9.10",
    "websockets>=14.2",
]
